title: "Hoshimov Mirzohamidullo"
logo: /assets/photo.png
description: "Junior Data Scientist | Machine Learning Enthusiast | Student at Woosong University"
show_downloads: true
theme: jekyll-theme-minimal
